package com.etc.view;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;

import com.etc.dao.DoctorDao;
import com.etc.pojo.Doctor;

import com.etc.pojo.Patient;
import com.etc.service.DoctorService;

import com.etc.service.PatientService;
import com.etc.util.ToolsUtil;
import com.etc.pojo.staticAll;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class DoctorSelectView extends javax.swing.JFrame {
	
	private static DoctorService doctorService = new DoctorService();
	
	private static String doctorName = null; // 查询条件

    /**
     * Creates new form DoctorSelectView
     */
    public DoctorSelectView() {
        initComponents();
        // 设置标题
      	this.setTitle("超级医院挂号系统");
      // 设置可见
      this.setVisible(true);
      // 设置伸缩
      this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ReturnButton3 = new javax.swing.JButton();
        ComfirmButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DoctorTable1 = new javax.swing.JTable();
        SelectTextField = new javax.swing.JTextField();
        SelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("隶书", 2, 24)); // NOI18N
        jLabel1.setText("*查询医生信息*");

        ReturnButton3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ReturnButton3.setForeground(new java.awt.Color(204, 0, 0));
        ReturnButton3.setText("返   回");
        ReturnButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReturnButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButton3ActionPerformed(evt);
            }
        });

        ComfirmButton3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ComfirmButton3.setForeground(new java.awt.Color(0, 51, 153));
        ComfirmButton3.setText("退   出");
        ComfirmButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ComfirmButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComfirmButton3ActionPerformed(evt);
            }
        });

        DoctorTable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        
       
        DoctorTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                DoctorTable1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DoctorTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                DoctorTable1AncestorRemoved(evt);
            }
        });
        

        Object [][] doctorArray = null;
        
        // 查询商品信息
       try {
		List<Doctor> goodses = doctorService.queryDoctor(doctorName);
		// 将 list 转为 二维数据
		doctorArray = ToolsUtil.loadCartsArray(goodses);
	} catch (SQLException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		JOptionPane.showInternalMessageDialog(this, e.getMessage());
		return;
	}
        
       DoctorTable1.setModel(new javax.swing.table.DefaultTableModel(
    		   doctorArray,
            new String [] {
                "ID", "姓名", "专业", "科室", "当前挂号人数",
            }
        ));
       jScrollPane2.setViewportView(DoctorTable1);
       
       
        SelectTextField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        SelectTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectTextFieldActionPerformed(evt);
            }
        });

        SelectButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        SelectButton.setText("查  询");
        SelectButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        
        
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ReturnButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComfirmButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(SelectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(SelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComfirmButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void ReturnButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	doctorName = null;
    	this.dispose();
        ChooseView ChooseView = new ChooseView();
    }                                             

    private void ComfirmButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	
    	System.exit(-1);
    }                                              

    private void SelectTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    	
   
    }                                               

    private void DoctorTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void DoctorTable1AncestorMoved(javax.swing.event.AncestorEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void DoctorTable1AncestorRemoved(javax.swing.event.AncestorEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	
    	// 获取商品名称
    	String qGoodsName = SelectTextField.getText().trim();
    			
    	doctorName = qGoodsName; // 交个全局变量 作为查询条件
    	// 重新渲染该页面
    	this.dispose();
    	DoctorSelectView doctorSelectView = new DoctorSelectView();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorSelectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ComfirmButton3;
    private javax.swing.JTable DoctorTable1;
    private javax.swing.JButton ReturnButton3;
    private javax.swing.JButton SelectButton;
    private javax.swing.JTextField SelectTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration                   
}

/**
*确认：ComfirmButton3;
  *  医生选择键：DoctorComboBox;
  *返回：ReturnButton3;
  *显示医生信息标签 ：jLabel3
  */