/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etc.view;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;

import com.etc.dao.DoctorDao;
import com.etc.pojo.Doctor;

import com.etc.pojo.Patient;
import com.etc.service.DoctorService;

import com.etc.service.PatientService;
import com.etc.util.ToolsUtil;
import com.etc.pojo.staticAll;

/**
 *
 * @author lenovo
 */
public class DoctorSystemView extends javax.swing.JFrame {
	
	private static DoctorService doctorService = new DoctorService();
	
	private static String doctorName = staticAll.getUserName(); // 查询条件

    /**
     * Creates new form DoctorSystemView
     */
    public DoctorSystemView() {
        initComponents();
        
        // 设置标题
      	this.setTitle("超级医院挂号系统");
      // 设置可见
      this.setVisible(true);
      // 设置伸缩
      this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorInfoTable = new javax.swing.JTable();
        ExitButton2 = new javax.swing.JButton();
        InterrogationButton = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("隶书", 0, 24)); // NOI18N
        jLabel1.setText("*医生系统*");

        DoctorInfoTable.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        Object [][] doctorArray = null;
     // 查询商品信息
        try {
 		List<Doctor> goodses = doctorService.queryDoctor(doctorName);
 		// 将 list 转为 二维数据
 		doctorArray = ToolsUtil.loadCartsArray(goodses);
 	} catch (SQLException e) {
 		// TODO Auto-generated catch block
 		e.printStackTrace();
 		JOptionPane.showInternalMessageDialog(this, e.getMessage());
 		return;
 	}
         
        DoctorInfoTable.setModel(new javax.swing.table.DefaultTableModel(
     		   doctorArray,
             new String [] {
                 "ID", "姓名", "专业", "科室", "当前挂号人数"
             }
         ));

        
        DoctorInfoTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                DoctorInfoTableAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DoctorInfoTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                DoctorInfoTableAncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(DoctorInfoTable);

        ExitButton2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        ExitButton2.setForeground(new java.awt.Color(153, 0, 0));
        ExitButton2.setText("退   出");
        ExitButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        ExitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton2ActionPerformed(evt);
            }
        });

        InterrogationButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        InterrogationButton.setForeground(new java.awt.Color(0, 102, 153));
        InterrogationButton.setText("进入问诊");
        InterrogationButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        InterrogationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterrogationButtonActionPerformed(evt);
            }
        });

        jButton111.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton111.setText("查看病人");
        jButton111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton111ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(ExitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(InterrogationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InterrogationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>                        

    private void InterrogationButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        
        /**
         * 进入问诊界面
         * @param evt
         */                                             
        // TODO add your handling code here:
    	this.dispose();
    	InquirySystemView inquirySystemView = new InquirySystemView();
    }                                                   

    private void ExitButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
        System.exit(-1);
    	
    }                                           

    private void DoctorInfoTableAncestorRemoved(javax.swing.event.AncestorEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void DoctorInfoTableAncestorAdded(javax.swing.event.AncestorEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void DoctorInfoTableAncestorMoved(javax.swing.event.AncestorEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jButton111ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	
    	/**
         * 进入查看患者界面
         * @param evt
         */                                             
        // TODO add your handling code here:
        this.dispose();
        PatientSelfView patientSelfView = new PatientSelfView();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorSystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorSystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorSystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorSystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorSystemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable DoctorInfoTable;
    private javax.swing.JButton ExitButton2;
    private javax.swing.JButton InterrogationButton;
    private javax.swing.JButton jButton111;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
/**医生信息表：DoctorInfoTable;
*退出：ExitButton2;
*进入问诊： InterrogationButton;
*/